### ISSUE TITLE
Adicionar rock no jogo

### ISSUE THREAD

**Issue by MatheusBD15** [MarlonVCendron/mypoggers-game#1]
* **Estou enviando uma ...**
  - [x] sinalização de bug
  - [ ] solicitação de funcionalidade

* **Qual o comportamento atual?**

Não tem rock no jogo.

* **Qual é o comportamento esperado?**

Ter rock no jogo.

* **Qual a motivação da mudança desse comportamento?**

Fodase a dilma vou escutar rock  ☠️ 🤘

**Comment by MarlonVCendron** [comment]
Corrigido no PR https://github.com/MarlonVCendron/mypoggers-game/pull/2
